# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: 'sudo npm install -g esy@next --unsafe-perm'
  displayName: 'Installing deps'
  workingDirectory: 're'

- script: esy install
  displayName: 'Installing deps'
  workingDirectory: 're'

- script: esy build
  displayName: 'Building'
  workingDirectory: 're'

- script: esy x Pesy.exe
  displayName: 'Test run Pesy.exe'
  workingDirectory: 're'

- script: esy test
  displayName: 'Running tests'
  workingDirectory: 're'
