parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g @esy-nightly/esy --unsafe-perm'
      displayName: 'Installing deps'
      workingDirectory: 're'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g @esy-nightly/esy --unsafe-perm'
      displayName: 'Installing deps'
      workingDirectory: 're'
  - script: esy install
    displayName: 'Installing deps'
    workingDirectory: 're'
  - script: esy build
    displayName: 'Building'
    workingDirectory: 're'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: ./_build/install/default/bin/TestPesy.exe
      displayName: 'Running tests'
      workingDirectory: 're'
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: .\_build\install\default\bin\TestPesy.exe
      displayName: 'Running tests'
      workingDirectory: 're'
