parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g @esy-nightly/esy@0.4.10-e6e1e7 --unsafe-perm'
      displayName: 'Installing deps'
      workingDirectory: 're'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g @esy-nightly/esy@0.4.10-e6e1e7 --unsafe-perm'
      displayName: 'Installing deps'
      workingDirectory: 're'
  - script: esy install
    displayName: 'Installing deps'
    workingDirectory: 're'
  - script: esy build
    displayName: 'Building'
    workingDirectory: 're'
  - script: esy npm-release
    displayName: 'Creating npm release'
    workingDirectory: 're'
  - script: npm pack
    displayName: 'NPM packing...'
    workingDirectory: 're/_release'
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g .\pesy-0.0.0.tgz --unsafe-perm'
      displayName: 'npm link... for tests'
      workingDirectory: 're/_release'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g ./pesy-0.0.0.tgz  --unsafe-perm'
      displayName: 'npm link... for tests'
      workingDirectory: 're/_release'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: ./_build/install/default/bin/TestPesy.exe
      displayName: 'Running tests'
      workingDirectory: 're'
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: .\_build\install\default\bin\TestPesy.exe
      displayName: 'Running tests'
      workingDirectory: 're'
